server: https://{{kubernetes_fqdn}}:{{RKE2_PORT}}
tls-san:
  - {{kubernetes_fqdn}}
token: {{rke2_token}}

data-dir: "{{rke_data_dir}}"
cluster-cidr: "{{cluster_cidr}}"
service-cidr: "{{service_cidr}}"
service-node-port-range: "{{service_node_port_range}}"
cluster-dns: "{{cluster_dns}}"
cluster-domain: "{{cluser_domain}}"

node-name: {{inventory_hostname}}
etcd-expose-metrics: true
etcd-snapshot-retention: 5
etcd-snapshot-schedule-cron: "0 */5 * * *"
etcd-snapshot-dir: "{{etcd_snapshot_dir}}"
  
{%if (cis_profile is defined) and (cis_profile != "") %}
profile: "{{cis_profile}}"
{% endif %}
protect-kernel-defaults: true
cni: "calico"
disable-kube-proxy: false
disable-scheduler: false
disable-cloud-controller: false

disable: 
  - rke2-ingress-nginx

