---
- hosts: worker
  become: yes
  tasks:
    - name: "Update /etc/hosts with kubernetes fqdn"
      lineinfile:
        path: /etc/hosts
        line: "{{ item.ip }}    {{ kubernetes_fqdn }}"
      with_items:
        - "{{lb}}"
    - name: "Create Rancher tree"
      file:
        path: "{{rancher_config_path}}"
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: "Setup protect kernel panic"
      template:
        src: templates/protect_kernel_panic.conf
        dest: /etc/sysctl.d/protect_kernel_panic.conf
      register: kernel_panic

    - name: "apply sysctl kubelet config"
      shell:
        cmd: sysctl -p /etc/sysctl.d/protect_kernel_panic.conf
      register: sysctl_cmd
      failed_when: "sysctl_cmd.rc != 0"
      when: kernel_panic is changed
    
    - name: "Push crictl config"
      template:
        src: crictl_config.yaml
        dest: "/etc/crictl.yaml"
        mode: 0644
        owner: root
        group: root

    - name: "Push RKE2 config"
      template:
        src: rke2_config_worker.yaml
        dest: "{{rancher_config_path}}/config.yaml"
        mode: 0644
        owner: root
        group: root
      register: push_config

    - name: "Exec RKE2 script"
      shell:
        cmd: |
          curl -sfL {{url_script_rke2}} | INSTALL_RKE2_TYPE="agent" sh  -s - --config {{rancher_config_path}}/config.yaml
      when: push_config is changed

    - name: "Start service RKE2"
      service:
        name: rke2-agent.service
        state: started
        enabled: yes
      when: push_config is changed
